services:
  postgis:
    image: postgis/postgis
    container_name: postgis-local
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: meetDB
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
